export const APP_CONFIG = {
    CODE_LENGTH: 6,
    CODE_MIN_LENGTH: 6,
    CODE_MAX_LENGTH: 6,
    TRIAL_HOURS: 24,
    PRO_HOURS: 72,
    EXPIRED_HOURS_THRESHOLD: 0,
    MS_PER_SECOND: 1000,
    SECONDS_PER_MINUTE: 60,
    MINUTES_PER_HOUR: 60,
    HOURS_PER_DAY: 24,
    ANALYTICS: {
        MAX_TRACKS_DISPLAY: 8,
        MAX_LABEL_LENGTH: 20,
        MAX_GENRES_DISPLAY: 6,
        ICON_SIZE: 14,
        CHEVRON_SIZE: 18,
    },
    MODERATION: {
        CONFIDENCE_HIGH: 80,
        CONFIDENCE_MEDIUM: 50,
        GEMINI_DEFAULT_CONFIDENCE: 0.8,
    },
    UI: {
        CAROUSEL_INTERVAL_MS: 5000,
        QR_CODE_SIZE_DEFAULT: 256,
        ICON_SIZE_MEDIUM: 20,
    }
} as const;
